       SELECT ACCOUNTS-FILE
       ASSIGN TO "accounts.idx"
       ORGANIZATION IS INDEXED
       ACCESS MODE IS DYNAMIC
       RECORD KEY IS ACCOUNT-KEY
       FILE STATUS IS F-ACCOUNT-STATUS.
       